apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/alexmchughdev/fixmycampus-client
  newName: ghcr.io/alexmchughdev/fixmycampus-client
  newTag: sha-bf897e4
- name: ghcr.io/alexmchughdev/fixmycampus-server
  newName: ghcr.io/alexmchughdev/fixmycampus-server
  newTag: sha-bf897e4
