apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/alexmchughdev/fixmycampus-client
  newName: ghcr.io/alexmchughdev/fixmycampus-frontend
  newTag: sha-80070f8
- name: ghcr.io/alexmchughdev/fixmycampus-server
  newName: ghcr.io/alexmchughdev/fixmycampus-backend
  newTag: sha-80070f8
